# Generated by Django 4.1.5 on 2023-01-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('editora', models.CharField(max_length=50, verbose_name='Editora')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_do_cadastro', models.DateField(auto_now_add=True)),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(verbose_name='Codigo')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('data_de_emprestimo', models.DateField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimos.livro')),
            ],
        ),
    ]
