# Generated by Django 4.1.4 on 2022-12-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(verbose_name='Codigo')),
                ('usuario', models.CharField(max_length=200, verbose_name='Usuario')),
                ('data_do_emprestimo', models.DateField(verbose_name='Data do Emprestimo')),
                ('livro', models.CharField(max_length=200, verbose_name='Livro')),
            ],
        ),
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('editora', models.CharField(max_length=200, verbose_name='Editora')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('data_do_cadastro', models.DateField(verbose_name='Data do Cadastro')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.PositiveIntegerField(verbose_name='CPF')),
            ],
        ),
    ]
