# Generated by Django 4.1.4 on 2022-12-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField(verbose_name='Codigo')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('data_de_emprestimo', models.DateField(verbose_name='Data de Emprestimo')),
                ('livro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('editora', models.CharField(max_length=50, verbose_name='Editora')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data_do_cadastro', models.DateField(verbose_name='Data do Cadastro')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
            ],
        ),
        migrations.DeleteModel(
            name='Emprestimo',
        ),
        migrations.DeleteModel(
            name='Livros',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
