# Generated by Django 4.1.5 on 2023-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='codigo',
            field=models.PositiveIntegerField(auto_created=True, verbose_name='Codigo'),
        ),
    ]
