# Generated by Django 4.1.5 on 2023-01-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_emprestimos_livro_delete_emprestimo_delete_livros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='livro',
            field=models.CharField(max_length=50, verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
