# Generated by Django 4.1.5 on 2023-01-28 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='codigo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Codigo'),
        ),
    ]
