# Generated by Django 4.1.5 on 2023-01-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_emprestimos_livro_alter_livro_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_de_emprestimo',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_do_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
    ]
