# Generated by Django 4.1.5 on 2023-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0004_alter_emprestimos_data_de_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='codigo',
            field=models.PositiveIntegerField(verbose_name='Codigo'),
        ),
    ]
